<?php

/**
 * @file
 * Test module for OG Context.
 */

/**
 * Implements hook_entity_view().
 *
 * Get the Group context for the entity being viewed and output it in a message
 * for the test to detect.
 */
function og_context_test_entity_view($entity, $type, $view_mode, $langcode) {
  $context = og_context($type);

  if ($context) {
    drupal_set_message(t("Got context of type !context-type with gid !gid", array(
      '!context-type' => $context['group_type'],
      '!gid' => $context['gid'],
    )));
  }
}
