<?php
// $Id$

/**
 * @file
 * Rules module functionality for the Organic groups module.
 */

/*******************************************************************************
 * Hook implementations
 ******************************************************************************/

/**
 * Implementation of hook_rules_event_info()
 *
 * TODO: http://drupal.org/node/596222
 */
function og_rules_event_info() {
  $items = array();

  return $items;
}