<?php


/**
 * @file
 * Test module for Organic groups.
 */

/**
 * Implements hook_node_access().
 */
function og_test_node_access($node, $op, $account) {
  $return = NODE_ACCESS_IGNORE;

  if ($op == 'update' && $node->title == 'deny access') {
    $return = NODE_ACCESS_DENY;
  }
  return $return;
}

/**
 * Implements hook_default_og_membership_type().
 */
function og_test_default_og_membership_type() {
  $items = array();
  $items['expire'] = entity_import('og_membership_type', '{
    "name" : "expire",
    "description" : "Expire",
    "rdf_mapping" : []
  }');
  return $items;
}