<?php
// $Id$

/**
 * @file
 * Install, update, and uninstall functions for the Organic groups access module.
 */

/**
 * Implements hook_uninstall().
 */
function og_access_uninstall() {
  $vars = array(
    'og_access_strict_private',
  );
  foreach ($vars as $var) {
    variable_del($var);
  }
}

/**
 * Implements hook_schema();
 */
function og_access_schema() {
  if (db_table_exists('og_access_post')) {
    db_rename_table('og_access_post', 'd6_og_access_post');
  }
}