<?php
// $Id$

/**
 * @file
 * Provide field access based on group.
 */

/**
 * Implements hook_og_fields_info_alter().
 *
 * Add default access fields values to fields, if they haven't provided
 * themselves.
 */
function og_field_access_og_fields_info_alter(&$fields_info) {
  // Add field access defaults.
  foreach ($fields_info as $field_name => &$value) {
    $value += array('allow field access' => TRUE);

    if ($value['allow field access']) {
      $label = $value['instance']['label'];
      $value += array(
        'field access' => array(
          'view' => array(
            'permission' => 'view ' . $field_name . ' field',
            'default permission' => array(
              OG_ANONYMOUS_ROLE,
              OG_AUTHENTICATED_ROLE,
              OG_ADMINISTRATOR_ROLE,
            ),
            'title' => t('View @label field', array('@label' => $label)),
            'description' => t('View the @label field for existing groups.', array('@label' => $label)),
          ),
          'edit' => array(
            'permission' => 'edit ' . $field_name . ' field',
            'default permission' => array(OG_ADMINISTRATOR_ROLE),
            'title' => t('Edit @label field', array('@label' => $label)),
            'description' => t('Edit the @label field for existing groups.', array('@label' => $label)),
          ),
        ),
      );
    }
  }
}

/**
 * Implements hook_og_permission_alter().
 */
function og_field_access_og_permission_alter(&$perms) {
  foreach (og_fields_info() as $field_name => $value) {
    if (!empty($value['allow field access']) && !empty($value['field access'])) {
      foreach ($value['field access'] as $perm) {
        $key = $perm['permission'];
        $perms[$key]['title'] = $perm['title'];
        $perms[$key]['description'] = $perm['description'];

        // Initialize the roles key, if other modules haven't set it explicetly.
        // This means the permissions can apply to anonymous and authenticated
        // members as-well.
        $perms[$key] += array('roles' => array(OG_ANONYMOUS_ROLE, OG_AUTHENTICATED_ROLE));

        // Add the module information, so the permissions will be assigned with
        // the correct module name, and not be associated with og_field_access.
        $perms[$perm['permission']]['module'] = $value['module'];
      }
    }
  }
}

/**
 * Implements hook_field_attach_form().
 *
 * Add access check on the field.
 */
function og_field_access_field_attach_form($entity_type, $entity, &$form, $form_state, $langcode) {
  // Add field access permissions.
  foreach (og_fields_info() as $field_name => $value) {
    if (!empty($value['allow field access']) && !empty($value['field access'])) {
      foreach ($value['field access'] as $perm_value) {
        og_field_access_attach_form_access($entity_type, $entity, $form, $form_state, $langcode, $field_name, $perm_value['permission']);
      }
    }
  }
}

/**
 * Helper function to check if a user has access to a field.
 *
 * @see hook_field_attach_form().

 * @param $entity_type
 * @param $entity
 * @param $form
 * @param $form_state
 * @param $langcode
 * @param $field_name
 *   The name of the field that the access is checked for.
  @param $perm_key
 *   The group permission name.
 */
function og_field_access_attach_form_access($entity_type, $entity, &$form, $form_state, $langcode, $field_name, $perm) {
  global $user;
  $account = $user;
  list($id) = entity_extract_ids($entity_type, $entity);
  if (!empty($form[$field_name]) && !empty($id)) {
    // Existing entity and the field exists.
    $access = FALSE;

    $field = og_fields_info($field_name);


    if (in_array('group', $field['type']) && $group = og_get_group($entity_type, $id)) {
      $access = og_user_access($group->gid, $perm);
    }
    // If there is no access, check if this is a group content.
    if (!$access && in_array('group content', $field['type']) && $gids = array_intersect(og_get_entity_groups('user', $account), og_get_entity_groups($entity_type, $entity))) {
      foreach ($gids as $gid) {
        if (og_user_access($gid, $perm)) {
          $access = TRUE;
          break;
        }
      }
    }
    $form[$field_name][LANGUAGE_NONE]['#access'] = $access;
  }
}