<?php
// $Id$

/**
 * @file
 * Install, update, and uninstall functions for the organic groups register.
 */

/**
 * Implement hook_enable().
 *
 * Add GROUP access fields to existing group content.
 */
function group_register_enable() {
  foreach (node_type_get_names() as $type => $name){
    if (group_is_group_type('node', $type)) {
      group_create_field('group_register', 'node', $type);
    }
  }
}
