<?php
// $Id:$

/**
 * @file
 * Views integration for the Group module.
 */


/**
 * Implementation of hook_views_api().
 */
function group_views_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implement hook_field_formatter_info().
 */
function group_views_field_formatter_info() {
  return array(
    'group_views_default' => array(
      'label' => t('Group Views'),
      'field types' => array('list_text'),
    ),
  );
}

/**
 * Implement group_fields_info().
 */
function group_views_group_fields_info() {
  $items['group_views'] = array(
    'type' => array('group'),
    'description' => t('Add organic groups Views field to fieldable entities that are groups.'),
    'field' => array(
      'field_name' => 'group_views',
      'type' => 'list_text',
      'cardinality' => 1,
      'settings' => array('allowed_values' => '', 'allowed_values_function' => 'group_views_field_allowed_values'),
    ),
    'instance' => array(
      'label' => t('Groups views'),
      'widget_type' => 'options_select',
      'display' => array(
        'full' => array(
          'label' => 'hidden',
          'type' => 'group_views_default',
        ),
        'teaser' => array(
          'label' => 'above',
          'type' => 'group_list_default',
        ),
      ),
    ),
  );

  return $items;
}


/**
 * Get all the Views.
 */
function group_views_field_allowed_values() {
  $return = array();
  foreach (views_get_all_views() as $view_id => $view) {
    if (empty($view->disabled)) {
      $view_name = check_plain($view->name);
      foreach($view->display as $display) {
        $return[$view_id . ' ' .$display->id] = $view_name . ' (' . check_plain($display->display_title) .')';
      }
    }
  }

  return $return;
}


/**
 * Organic group views field formatter.
 *
 * @return
 *   A rendered View.
 */
function theme_field_formatter_group_views_default($variables) {
  $element = $variables['element'];
  $output = '';
  if (!empty($element['#item']['gid'])) {
    $view = explode(' ', $element['#item']['gid']);
    $output = views_embed_view($view[0], $view[1]);
  }

  return $output;
}
