<?php
// $Id$

/**
 * @file
 * Group UI.
 */

/**
 * Implement hook_menu().
 */
function group_ui_menu() {
  $items['group/%/%/subscribe'] = array(
    'type' => MENU_CALLBACK,
    'file' => 'group_ui.pages.inc',
    'page callback' => 'group_ui_subscribe',
    'page arguments' => array(1, 2),
    // Function will take care of permissions, as we want to show "you are
    // already a member of the group" to group members, however it is not
    // possible to give authenticated group members the "subscribe" permissions.
    'access callback' => 'user_is_logged_in',

    // We don't add the group name, as it might be private.
    'title' => 'Join group'
  );

  $items['group/%/%/unsubscribe'] = array(
    'type' => MENU_CALLBACK,
    'file' => 'group_ui.pages.inc',
    'page callback' => 'group_ui_unsubscribe',
    'page arguments' => array(1, 2),
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('unsubscribe', 1, 2),
    'title' => 'Leave group',
  );

  $items['group/%/%/invite'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('group_ui_invite_form', 1, 2),
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('invite', 1, 2),
    'title' => 'Send invitation',
    'type' => MENU_CALLBACK,
    'file' => 'group_ui.pages.inc',
  );

  $items['group/%/%/admin/people/add-user'] = array(
    'page callback' => 'drupal_get_form',
    'title' => 'Add members',
    'page arguments' => array('group_ui_add_users', 1, 2),
    'type' => MENU_LOCAL_TASK,
    'file' => 'group_ui.admin.inc',
    'weight' => 5,
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('add user', 1, 2),
  );

  // User listing pages.
  $items['group/%/%/admin/people'] = array(
    'title arguments' => array('People in group @group', 1, 2),
    'title callback' => 'group_ui_menu_title_callback',
    'description' => 'Find and manage group members.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('group_ui_user_admin_account', 1, 2),
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('administer group', 1, 2),
    'weight' => -4,
    'file' => 'group_ui.admin.inc',
  );

  // Permission administration pages.
  $items['group/%/%/admin/people/roles'] = array(
    'title arguments' => array('Roles for group @group', 1, 2),
    'title callback' => 'group_ui_menu_title_callback',
    'description' => 'List, edit, or add user roles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('group_ui_user_admin_new_role', 1, 2),
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('administer group', 1, 2),
    'file' => 'group_ui.admin.inc',
    'weight' => -9,
  );

  $items['group/%/%/admin/people/roles/edit'] = array(
    'title' => 'Edit role',
    'page arguments' => array('group_ui_user_admin_role', 1, 2),
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('administer group', 1, 2),
    'type' => MENU_CALLBACK,
  );

  $items['group/%/%/admin/people/permissions'] = array(
    'title arguments' => array('Permissions for group @group', 1, 2),
    'title callback' => 'group_ui_menu_title_callback',
    'description' => 'Determine access to features by selecting permissions for roles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('group_ui_user_admin_permissions', 1, 2),
    'access callback' => 'group_user_access_by_entity',
    'access arguments' => array('administer group', 1, 2),
    'file' => 'group_ui.admin.inc',
    'weight' => -8,
  );

  foreach (entity_get_info() as $entity => $value) {
    if ($value['fieldable']) {
      $items["$entity/%/group"] = array(
        'title' => 'Group',
        'page callback' => 'group_ui_group_admin_overview',
        'page arguments' => array($entity, 1),
        'access callback' => 'group_user_access_by_entity',
        'access arguments' => array('administer group', $entity, 1),
        'type' => MENU_LOCAL_TASK,
        'file' => 'group_ui.admin.inc',
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
      );
    }
  }

  $items['admin/config/group'] = array(
    'title' => 'Group',
    'description' => 'Administer the suite of Group modules.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/group/permissions'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('group_ui_user_admin_global_permissions'),
    'title' => 'Group global permissions',
    'access arguments' => array('administer site configuration'),
    'description' => 'Configure organic groups global permissions.',
    'file' => 'group_ui.admin.inc',
  );
  $items['admin/config/group/fields'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('group_ui_field_settings'),
    'title' => 'Group field settings',
    'access arguments' => array('administer site configuration'),
    'description' => 'Configure organic groups fields in bundles.',
    'file' => 'group_ui.admin.inc',
  );

  return $items;
}

/**
 * Menu callback; Return the title of a menu item based on the group title.
 */
function group_ui_menu_title_callback($title, $entity_type, $etid) {
  $label = check_plain(group_entity_get_label($entity_type, $etid));
  return str_replace('@group', $label, $title);
}

/**
 * Implement hook_theme().
 */
function group_ui_theme() {
  return array(
    'group_ui_user_admin_permissions' => array(
      'render element' => 'form',
      'file' => 'group_ui.admin.inc',
    ),
    'group_ui_user_admin_bundles' => array(
      'render element' => 'form',
      'file' => 'group_ui.admin.inc',
    ),
    'group_ui_user_admin_new_role' => array(
      'render element' => 'form',
      'file' => 'group_ui.admin.inc',
    ),
  );
}


/**
 * Implement hook_field_formatter_info().
 */
function group_ui_field_formatter_info() {
  return array(
    'group_group_subscribe' => array(
      'label' => t('Group subscription'),
      'field types' => array('list_boolean'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function group_ui_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  if ($field['field_name'] == 'group_group' && $links = group_ui_subscribe_link($entity_type, $entity)) {
    $element[0] = $links;
  }

  return $element;
}


/**
 * Return a subscribe link according to user's permissions.
 *
 * @param $entity_type
 * @param $entity
 * @param $account
 * @return unknown_type
 */
function group_ui_subscribe_link($entity_type, $entity, $account = NULL) {
  $return = array();

  if (empty($account)) {
    global $user;
    $account = $user;
  }

  list($id) = entity_extract_ids($entity_type, $entity);

  if (($group = group_get_group($entity_type, $id))) {
    if (!empty($entity->uid) && ($entity->uid == $user->uid)) {
      // User is the group manager.
      $return = array(
        '#type' => 'item',
        '#markup' => t('You are the group manager'),
      );
    }
    else {
      // check the user state.
      if ($state = group_get_entity_state($group->gid, 'user', $account)) {

        if ($state == GROUP_STATE_PENDING && group_user_access($group->gid, 'subscribe')) {
          $links['title'] = t('Re-request group membership');
          $links['href'] = "group/$entity_type/$id/subscribe";
        }
        elseif ($state == GROUP_STATE_ACTIVE && group_user_access($group->gid, 'unsubscribe', $account)) {
          $links['title'] = t('Unsubscribe from group');
          $links['href'] = "group/$entity_type/$id/unsubscribe";
        }
      }
      else {
        if (group_user_access($group->gid, 'subscribe without approval', $account)) {
          $links['title'] = t('Subscribe to group');
        }
        elseif (group_user_access($group->gid, 'subscribe')) {
          $links['title'] = t('Request group membership');
        }
        $links['href'] = "group/$entity_type/$id/subscribe";
      }

      if (!empty($links['title'])) {
        $return = array(
          '#type' => 'link',
          '#title' => $links['title'],
          '#href' => $links['href'],
        );
      }
    }
  }

  return $return;
}

/**
 * Implement hook_forms().
 */
function group_ui_forms() {
  $forms['group_ui_user_admin_new_role']['callback'] = 'group_ui_user_admin_role';

  // Form to define the default permissions state for new groups.
  $forms['group_ui_user_admin_global_permissions']['callback'] = 'group_ui_user_admin_permissions';

  return $forms;
}

/**
 * Implement hook_form_FORM_ID_alter().
 */
function group_ui_form_node_type_form_alter(&$form, &$form_state) {
  $node_type = $form['#node_type']->type;

  $form['group'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group'),
    '#collapsible' => TRUE,
    '#group' => 'additional_settings',
    '#description' => t('Specify how organic groups should treat content of this type. Content may behave as a group, as group content, or may not participate in organic groups at all.'),
  );

  $form['group']['group_group_type'] = array(
    '#type' => 'radios',
    '#title' => t('Group'),
    '#default_value' =>  group_is_group_type('node', $node_type) ? 'group' : 'omitted',
    '#options' => array('omitted' => t('Not a group type'), 'group' => t('Group type')),
  );

  $form['group']['group_group_content_type'] = array(
    '#type' => 'radios',
    '#title' => t('Group content'),
    '#default_value' =>  group_is_group_content_type('node', $node_type) ? 'group_content' : 'omitted',
    '#options' => array('omitted' => t('Not a group content type'), 'group_content' => t('Group content type')),
  );
}

/**
 * Implement hook_group_permission().
 */
function group_ui_group_permission() {
  return array(
    'subscribe' => array(
      'title' => t('Subscribe user to group'),
      'description' => t("Allow user to be a member of a group (approval required)."),
      'roles' => array(GROUP_ANONYMOUS_ROLE),
    ),
    'subscribe without approval' => array(
      'title' => t('Subscribe user to group (no approval required).'),
      'description' => t("Allow user to be a member of a group without an approval of the group administrator."),
      'roles' => array(GROUP_ANONYMOUS_ROLE),
    ),
    'unsubscribe' => array(
      'title' => t('Unsubscribe user from group'),
      'description' => t("Allow user to be remove membership from a group."),
      'roles' => array(GROUP_AUTHENTICATED_ROLE),
    ),
    'approve and deny subscription' => array(
      'title' => t('Approve and deny subscription'),
      'description' => t("Allow user to allow or deny another user's subscription request."),
    ),
    'add user' => array(
      'title' => t('Add user'),
      'description' => t("Add a new user to the group."),
    ),
  );
}

/**
 * Implement hook_group_default_permissions().
 */
function group_ui_group_default_permissions() {
  return array(
    'subscribe' => array(GROUP_ANONYMOUS_ROLE),
    'unsubscribe' => array(GROUP_AUTHENTICATED_ROLE),
  );
}



/**
 * Implement hook_group_user_operations().
 */
function group_ui_group_user_operations($form = array(), $form_state = array()) {
  $gid = $form_state['group']->gid;
  $operations = array(
    'unblock' => array(
      'label' => t('Approve membership of the selected users'),
      'callback' => 'group_ui_user_operations_approve',
    ),
    'deny' => array(
      'label' => t('Deny membership from the selected users'),
      'callback' => 'group_ui_user_operations_deny',
    ),
    'block' => array(
      'label' => t('Block membership from the selected users'),
      'callback' => 'group_ui_user_operations_block',
    ),
  );

  if (group_user_access($gid, 'administer group')) {
    $roles = group_user_roles($gid);

    $add_roles = array();
    foreach ($roles as $rid => $name) {
      if (!in_array($name, array(GROUP_ANONYMOUS_ROLE, GROUP_AUTHENTICATED_ROLE))) {
        $add_roles['add_role-' . $rid] = strip_tags($name);
      }
    }

    $remove_roles = array();
    foreach ($roles as $rid => $name) {
      if (!in_array($name, array(GROUP_ANONYMOUS_ROLE, GROUP_AUTHENTICATED_ROLE))) {
        $remove_roles['remove_role-' . $rid] = strip_tags($name);
      }
    }

    if ($add_roles) {
      $role_operations = array(
        t('Add a role to the selected users') => array(
          'label' => $add_roles,
        ),
        t('Remove a role from the selected users') => array(
          'label' => $remove_roles,
        ),
      );

      $operations += $role_operations;
    }
  }

  // If the form has been posted, we need to insert the proper data for
  // role editing if necessary.
  if (!empty($form_state['submitted'])) {
    $operation_rid = explode('-', $form_state['values']['operation']);
    $operation = $operation_rid[0];
    if ($operation == 'add_role' || $operation == 'remove_role') {
      $rid = $operation_rid[1];
      if (group_user_access($gid, 'administer group')) {
        $operations[$form_state['values']['operation']] = array(
          'callback' => 'group_ui_user_multiple_role_edit',
          'callback arguments' => array($operation, $rid),
        );
      }
      else {
        watchdgroup('security', 'Detected malicious attempt to alter protected user fields.', array(), WATCHDGROUP_WARNING);
        return;
      }
    }
  }

  return $operations;
}


/**
 * Callback function for admin mass approving users.
 */
function group_ui_user_operations_approve($gid, $uids) {
  _group_ui_user_operations_set_state($gid, $uids, GROUP_STATE_ACTIVE);
}

/**
 * Callback function for admin mass blocking users.
 */
function group_ui_user_operations_block($gid, $uids) {
  _group_ui_user_operations_set_state($gid, $uids, GROUP_STATE_BLOCKED);
}


/**
 * Set the state of a user in a group.
 *
 * @param $gid
 *   Group ID
 * @param $uids
 *   Uset IDs
 * @param $state
 *   The state to set the user in the group.
 */
function _group_ui_user_operations_set_state($gid, $uids, $state) {
  $accounts = user_load_multiple($uids);
  foreach ($accounts as $account) {
    group_group($gid, 'user', $account, $state);
  }
}


/**
 * Callback function for admin mass denying users.
 */
function group_ui_user_operations_deny($gid, $uids) {
  $accounts = user_load_multiple($uids);

  foreach ($accounts as $account) {
    group_ungroup($gid, 'user', $account);
  }
}


/**
 * Callback function for admin mass adding/ deleting a user role.
 */
function group_ui_user_multiple_role_edit($gid, $accounts, $operation, $rid) {
  switch ($operation) {
    case 'add_role':
      $accounts = user_load_multiple($accounts);
      foreach ($accounts as $account) {
        group_users_roles_grant($gid, $account->uid, $rid);

      }
      break;
    case 'remove_role':
      $accounts = user_load_multiple($accounts);
      foreach ($accounts as $account) {
        group_users_roles_revoke($gid, $account->uid, $rid);
      }
      break;
  }
}

/**
 * Implementation of hook_group_ui_get_group_admin()
 */
function group_ui_group_ui_get_group_admin($gid) {
  $items = array();

  $default_access = group_is_group_default_access($gid);

  $items['add_people'] = array(
    'title' => t('Add people'),
    'description' => t('Add group members.'),
    // The final URL will be "group/$entity_type/$etid/admin/people/add-user".
    // @see group_ui_group_admin_overview().
    'href' => 'admin/people/add-user',
  );

  $items['people'] = array(
    'title' => t('People'),
    'description' => t('Manage the group members.'),
    'href' => "admin/people",
  );

  $items['roles'] = array(
    'title' => !$default_access ? t('Roles') : t('Roles (read-only)'),
    'description' => !$default_access ? t('Manage the group roles.') : t('View the group roles.'),
    'href' => "admin/people/roles",
  );
  $items['permissions'] = array(
    'title' => !$default_access ? t('Permissions') : t('Permissions (read-only)'),
    'description' => !$default_access ? t('Manage the group permissions.') : t('View the group permissions.'),
    'href' => "admin/people/permissions",
  );

  return $items;
}

/**
 * Get all the group admin menu items.
 */
function group_ui_get_group_admin($gid) {
  $data = module_invoke_all('group_ui_get_group_admin', $gid);

  // Allow other modules to alter the menu items.
  drupal_alter('group_ui_get_group_admin', $data, $gid);

  return $data;
}
